// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Vercel only injects "Sensitive" env vars (like DATABASE_URL here) at
// runtime, not during the build step. `prisma generate` runs in
// postinstall during build and never actually connects to the database —
// it only reads schema.prisma — so config loading must not hard-fail when
// DATABASE_URL is unresolved at that point. Real commands that need a
// live connection (migrate, the app itself at runtime) always have it set.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
